#!/bin/bash

set -euo pipefail

script_dir="$(dirname "${BASH_SOURCE[0]}")"
root="$(realpath "$script_dir")"

packages=("calendar" "client" "core" "notes" "server" "storage" "tasks")

sub="${1:-help}"

case "$sub" in
	"list" | "ls")
		{ for pkg in "${packages[@]}"; do
			echo "$pkg" $(jq ".version" "$root/$pkg/package.json" | tr -d '\"')
		done
		} | column -t
		;;
	"create-tags")
		for pkg in "${packages[@]}"; do
			v="$(jq -r ".version" "$root/$pkg/package.json")"
			tag="$pkg@$v"
			if ! git -C "$root" rev-parse "$tag" >/dev/null 2>&1; then
				git -C "$root" tag "$tag" -m "$tag"
				echo "Created tag $tag"
			fi
		done
		;;
	"force-update")
		pkg="${2:?Package name required}"
		v="$(jq -r ".version" "$root/$pkg/package.json")"
		tag="$pkg@$v"
		git -C "$root" tag -f "$tag" -m "$tag"
		;;
	"diff")
		pkg="${2:?Package name required}"
		if [ -n "${3:-}" ]; then
			tag="$pkg@$3"
		else
			tag="$(git tag --list "$pkg@*" --sort=-v:refname | head -n 1)"
		fi
		if [ -z "$tag" ]; then
			echo "No tags found for '$pkg'"
			exit 1
		fi
		git diff "$tag..main" -- "$pkg"
		;;
	"changed")
		for pkg in "${packages[@]}"; do
			latest_tag="$(git tag --list "$pkg@*" --sort=-v:refname | head -n 1)"
			if [ -z "$latest_tag" ]; then
				echo "$pkg (no releases)"
				continue
			fi
			if ! git diff --quiet "$latest_tag..main" -- "$pkg"; then
				echo "$pkg"
			fi
		done
		;;
	"log")
		if [ -n "${2:-}" ]; then
			pkg="${2}"
			latest_tag="$(git -C "$root" tag --list "$pkg@*" --sort=-v:refname | head -n 1)"
			if [ -z "$latest_tag" ]; then
				echo "No tags found for '$pkg'"
				exit 1
			fi
			git -C "$root" log "$latest_tag..main" --format=%B -- "$pkg" | sed '/^$/d'
		else
			for pkg in "${packages[@]}"; do
				latest_tag="$(git -C "$root" tag --list "$pkg@*" --sort=-v:refname | head -n 1)"
				if [ -z "$latest_tag" ]; then
					echo "No tags found for '$pkg'"
					continue
				fi
				output="$(git -C "$root" log "$latest_tag..main" --format=%B -- "$pkg" | sed '/^$/d')"
				if [ -z "$output" ]; then
					continue
				fi

				echo "--- $pkg ---"
				echo "$output"
			done
		fi
		;;
	"patch"|"minor"|"major")
		pkg="${2:?Package name required}"

		if [ -n "$(git -C "$root" status --porcelain)" ]; then
			echo "Working directory is not clean."
			exit 1
		fi
		tag=$(cd "$root/$pkg" && npm version "$sub" --tag-version-prefix="$pkg@" --message "$pkg@%s" 2>/dev/null | sed -n 2p)
		if [[ "$tag" != "$pkg@"* ]]; then
			echo "Got invalid tag name from 'npm version': $tag"
			exit 1
		fi
		last_tag="$(git -C "$root" tag --list "$pkg@*" --sort=-v:refname | head -n 1)"
		git -C "$root" add "$pkg/package.json" "package-lock.json"
		git -C "$root" commit -m "$tag"
		git -C "$root" tag "$tag" -m "$tag"
		changelog="+ $(git -C "$root" log ${last_tag:+"$last_tag..main"} --format=%B -- "$pkg" | sed '/^$/d')"
		git -C "$root" push --follow-tags
		echo ""
		echo "$changelog"
		;;
	"history")
		pkg="${2:?Package name required}"
		git tag --list "$pkg@*" | sed "s/^$pkg@//" | sort -V
		;;
	"help" | *)
		cat << EOF
Usage: $0 <command>

Commands:
    list, ls                  List current versions in package.json files
    create-tags               Create git tags for current versions if they don't exist
    force-update <pkg>        Force update release tag for the current version of the given package
    diff <pkg> [version]      Show diff between the the specified or last tagged version and main for the given package
    changed                   List packages that have changed since their last release
    log [pkg]                 List commits since the last release for the given package, or all packages if none specified
    history <pkg>             List releases for the given package
    patch|minor|major <pkg>   Create a new release for the given package
    help                      Show this help message
EOF
		if [ "$sub" != "help" ]; then
			exit 1
		fi
		;;
esac 