/**
 * Loading translations from disk and generating types for their keys.
 * @module
 */

import type { Command } from 'commander';
import * as io from 'ioium/node';
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, join, resolve } from 'node:path';
import { deepAssign } from 'utilium';
import { extendLocale, loadedLocales, type LocaleData } from '../locales.js';

/**
 * Read every `<language>.json` file in a directory, without registering them.
 */
export function read(dir: string): Record<string, LocaleData> {
	const locales: Record<string, LocaleData> = {};

	for (const entry of readdirSync(dir)) {
		if (!entry.endsWith('.json')) continue;
		locales[basename(entry, '.json')] = JSON.parse(readFileSync(join(dir, entry), 'utf8'));
	}

	return locales;
}

/**
 * Load the translations in a directory into the current process.
 * @returns the languages that were loaded
 */
export function load(dir: string): string[] {
	const locales = read(dir);
	for (const [language, data] of Object.entries(locales)) extendLocale(language, data);
	return Object.keys(locales);
}

/**
 * Merge the languages in a directory into a single object.
 * `en` is applied last since it is the reference language.
 */
export function merge(locales: Record<string, LocaleData>): LocaleData {
	const merged: LocaleData = {};
	for (const [language, data] of Object.entries(locales)) {
		if (language != 'en') deepAssign(merged, data);
	}
	if (locales.en) deepAssign(merged, locales.en);
	return merged;
}

const replacementPattern = /\{(\w+)\}/g;

/**
 * Flatten nested translation data into `some.dotted.key` / translation pairs.
 * Arrays are flattened using their indices, e.g. `audit_severity.0`.
 */
export function* flatten(data: LocaleData, prefix: string = ''): Generator<[key: string, translation: string]> {
	for (const [key, value] of Object.entries(data)) {
		const path = prefix ? `${prefix}.${key}` : key;
		if (typeof value == 'string') yield [path, value];
		else yield* flatten(value as LocaleData, path);
	}
}

function quote(key: string): string {
	return `'${key.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;
}

/**
 * Generate the source of a module declaring the translation keys in `data` and the replacements each of them needs.
 */
export function generateTypes(data: LocaleData): string {
	let source = `// Generated by \`axium locales typegen\`. Do not edit.
import type {} from '@axium/core/locales';

declare module '@axium/core/locales' {
	interface LocaleKeys {
`;

	for (const [key, translation] of flatten(data)
		.toArray()
		.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))) {
		const names = new Set(Array.from(translation.matchAll(replacementPattern), ([, name]) => name));
		const replacements = names.size ? `{ ${Array.from(names, name => `${name}: LocaleValue`).join('; ')} }` : '{}';

		source += `		${quote(key)}: ${replacements};\n`;
	}

	source += `	}
}
`;

	return source;
}

export function createCommand<C extends Command>(parent: C) {
	const cmd = parent.command('locales');

	cmd.command('list')
		.description('List available locales')
		.action(() => console.log(Object.keys(loadedLocales).join(', ')));

	cmd.command('typegen')
		.description('Generate types for the translation keys of a package')
		.argument('[dir...]', 'the package directories to generate types for', ['.'])
		.option('-o, --output <path>', 'where to write the generated module, relative to each directory', 'src/.locale.ts')
		.action((dirs: string[], opt) => {
			for (const dir of dirs.map(d => resolve(d))) {
				const localesDir = join(dir, 'locales');
				if (!existsSync(localesDir)) {
					io.debug('No locales in', dir);
					continue;
				}

				const output = resolve(dir, opt.output);

				mkdirSync(dirname(output), { recursive: true });
				writeFileSync(output, generateTypes(merge(read(localesDir))), 'utf8');

				console.log('Generated', output);
			}
		});
}
