name: Continuous Integration

on:
    push:
        branches:
            - main
    workflow_dispatch:
    workflow_call:
    pull_request:

jobs:
    ci:
        name: CI
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        permissions:
            contents: write
            id-token: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4

            - name: Install dependencies
              run: npm install

            - name: Formatting
              run: npm run format:check

            - name: Linting
              run: npm run lint

            - name: Build (TypeScript)
              run: npx tsc -b

            - name: Build server (Vite)
              run: (cd server && npx vite build)

            - name: Write server JSON schema
              run: npm run write-schema
